# serverless.yml

service: sspes-layer

provider:
  name: aws
  runtime: java11
  stage: dev
  region: eu-north-1

# you can add packaging information here
package:
  individually: true
  include:
    - "**"

layers:
  apiLayer:
    path: ./target/deploy
    description: the original SSPES API as Layer
    name: sspesApiLayer


